version: '3.9'

services:
  base-node:
    image: base-node
    build:
      context: .
      dockerfile: Dockerfile

  mongo:
    image: mongo
    ports:
      - 27016:27017
    networks:
      - app-net

  gateway:
    image: base-node
    ports:
      - 3032:3032
    networks:
      - app-net
    environment:
      - APP_NAME=api-gateway
    command: './init.sh'
    volumes:
      - "./apps:/project/apps:ro"
      - "./libs:/project/libs:ro"

  auth-service:
    image: base-node
    networks:
      - app-net
    environment:
      - APP_NAME=auth-service
    command: './init.sh'
    volumes:
      - "./apps:/project/apps:ro"
      - "./libs:/project/libs:ro"

  user-service:
    image: base-node
    networks:
      - app-net
    environment:
      - APP_NAME=user-service
    command: './init.sh'
    volumes:
      - "./apps:/project/apps:ro"
      - "./libs:/project/libs:ro"

  todo-service:
    image: base-node
    networks:
      - app-net
    environment:
      - APP_NAME=todo-service
    command: './init.sh'
    volumes:
      - "./apps:/project/apps:ro"
      - "./libs:/project/libs:ro"

networks:
  app-net:
