version: '3.9'

services:
  base-node:
    image: base-node
    build:
      context: .
      dockerfile: Dockerfile

  gateway:
    image: base-node
    ports:
      - 3032:3032
    networks:
      - app-net
    environment:
      - APP_NAME=api-gateway
    command: './init.sh'

  user-service:
    image: base-node
    networks:
      - app-net
    environment:
      - APP_NAME=user-service
    command: './init.sh'

networks:
  app-net:
